# Generated by Django 2.2.4 on 2019-08-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=300)),
                ('nomeContato', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
