# Generated by Django 2.2.5 on 2019-09-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('qtdQuartos', models.PositiveIntegerField(verbose_name='Quantidade de quartos')),
                ('proprietario', models.CharField(max_length=60, verbose_name='Proprietário')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
