# Generated by Django 2.2.5 on 2019-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data da criação')),
                ('tipo_despesa', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('forma_pagamento', models.CharField(max_length=30)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
