# Generated by Django 2.2.5 on 2019-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('data_nascimento', models.DateField(verbose_name='Dat de nascimento')),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
