# Generated by Django 2.2.4 on 2019-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=128)),
                ('unidadeCompra', models.CharField(max_length=30)),
                ('qtdPrevistoMes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precoMaximo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
